name: Build Kernel for OnePlus Nord 3 (MT6983)
on:
  workflow_dispatch:
    inputs:
      KERNEL_SOURCE_URL:
        description: 'URL to the kernel source code'
        required: true
        default: 'https://github.com/OnePlusOSS/android_kernel_5.10_oneplus_mt6983'
      KERNEL_SOURCE_BRANCH:
        description: 'Branch of the kernel source'
        required: true
        default: 'oneplus/mt6983_v_15.0.0_nord_3'
      KERNEL_MODULES_URL:
        description: 'URL to the kernel modules repository'
        required: true
        default: 'https://github.com/OnePlusOSS/android_kernel_modules_oneplus_mt6983'
      KERNEL_MODULES_BRANCH:
        description: 'Branch of the kernel modules repository'
        required: true
        default: 'oneplus/mt6983_v_15.0.0_nord_3'
      BUILD_USER:
        description: 'Custom user name embedded in the kernel version string (uname -a)'
        required: false
        default: 'MyBuild'
      CUSTOM_SUFFIX:
        description: 'Custom suffix for the kernel version string and zip file name (leave empty for random)'
        required: false
        default: 'MyKernel'
      FAST_BUILD:
        type: boolean
        description: 'Enable fast build using a specific Clang toolchain and ccache?'
        required: true
        default: true

jobs:
  build:
    name: Build Kernel for OnePlus Nord 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libssl-dev libncurses5-dev bc bison flex libelf-dev ccache

      - name: Install Toolchain (Fast Build)
        if: ${{ github.event.inputs.FAST_BUILD == 'true' }}
        run: |
          echo "Setting up specific Clang toolchain for Fast Build"
          git clone https://github.com/ZyCromer/azure-clang --depth=1 clang-toolchain

      - name: Install Toolchain (Standard Build)
        if: ${{ github.event.inputs.FAST_BUILD == 'false' }}
        run: |
          echo "Setting up GCC toolchain for Standard Build"
          git clone https://github.com/mvaisakh/gcc-arm64.git --depth=1 gcc-arm64
          git clone https://github.com/mvaisakh/gcc-arm.git --depth=1 gcc-arm

      - name: Set up Ccache
        if: ${{ github.event.inputs.FAST_BUILD == 'true' }}
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref }}-

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 --single-branch -b ${{ github.event.inputs.KERNEL_SOURCE_BRANCH }} ${{ github.event.inputs.KERNEL_SOURCE_URL }} kernel

      - name: Clone and Place Kernel Modules
        run: |
          git clone --depth=1 --single-branch -b ${{ github.event.inputs.KERNEL_MODULES_BRANCH }} ${{ github.event.inputs.KERNEL_MODULES_URL }} kernel_modules
          mkdir -p kernel/vendor
          mv kernel_modules/* kernel/vendor/

      - name: Set Custom Kernel Suffix
        id: suffix_step
        run: |
          SETLOCALVERSION_PATH="kernel/scripts/setlocalversion"
          FINAL_SUFFIX=""
          
          if [ -n "${{ github.event.inputs.CUSTOM_SUFFIX }}" ]; then
            FINAL_SUFFIX="${{ github.event.inputs.CUSTOM_SUFFIX }}"
          else
            # Generate a random suffix in the format from fast.txt
            RANDOM_DIGIT=$(od -An -N1 -tu1 < /dev/urandom | tr -d '[:space:]' | awk '{print $1 % 11}')
            RANDOM_HASH=$(od -An -N7 -tx1 /dev/urandom | tr -d ' \n')
            FINAL_SUFFIX="${RANDOM_DIGIT}-o-g${RANDOM_HASH}"
          fi
          
          echo "Final Suffix: $FINAL_SUFFIX"
          # Set output for later steps
          echo "suffix=$FINAL_SUFFIX" >> $GITHUB_OUTPUT

          # Modify the setlocalversion script to append the suffix
          if [ -f "$SETLOCALVERSION_PATH" ]; then
            echo "Modifying $SETLOCALVERSION_PATH to add suffix and remove -dirty tag"
            # Remove -dirty tag
            sed -i 's/ -dirty//g' "$SETLOCALVERSION_PATH"
            # Append the suffix before the final echo
            tac "$SETLOCALVERSION_PATH" | sed "0,/echo \"\\\$res\"/s//res=\"\\\$res-\$FINAL_SUFFIX\"; echo \"\\\$res\"/" | tac > "$SETLOCALVERSION_PATH.tmp" && mv "$SETLOCALVERSION_PATH.tmp" "$SETLOCALVERSION_PATH"
            chmod +x "$SETLOCALVERSION_PATH"
          else
            echo "Warning: $SETLOCALVERSION_PATH not found. Cannot apply custom suffix."
          fi

      - name: Configure and Build Kernel
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="${{ github.event.inputs.BUILD_USER }}"
          
          if [ "${{ github.event.inputs.FAST_BUILD }}" = "true" ]; then
            echo "Using specific Clang for build"
            export PATH="${{ github.workspace }}/clang-toolchain/bin:${PATH}"
            export CROSS_COMPILE="aarch64-linux-gnu-"
            export CC="ccache clang"
            export LD=ld.lld
            export AR=llvm-ar
            export NM=llvm-nm
            export OBJCOPY=llvm-objcopy
            export OBJDUMP=llvm-objdump
            export STRIP=llvm-strip
            export CFLAGS="-O3 -fno-PIC -Wno-error"
            export CXXFLAGS="-O3 -fno-PIC -Wno-error"
          else
            echo "Using GCC for build"
            export CROSS_COMPILE_ARM32=${{ github.workspace }}/gcc-arm/bin/arm-eabi-
            export CROSS_COMPILE=${{ github.workspace }}/gcc-arm64/bin/aarch64-elf-
          fi
          
          echo "--- Configuring Kernel ---"
          make O=out vendor/oplus_defconfig

          echo "--- Building Kernel Image and Modules ---"
          make -j$(nproc --all) O=out
          make -j$(nproc --all) O=out modules

      - name: Create AnyKernel3 Zip
        run: |
          # Clone AnyKernel3
          git clone https://github.com/osm0sis/AnyKernel3.git
          # Copy the kernel image
          cp kernel/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          # Create a directory for modules and copy them
          mkdir -p AnyKernel3/modules
          find kernel/out -type f -name "*.ko" -exec cp -f {} AnyKernel3/modules/ \;
          # Create the flashable zip with the dynamic suffix
          cd AnyKernel3
          zip -r9 ../Kernel-OnePlus-Nord-3-${{ steps.suffix_step.outputs.suffix }}.zip * -x .git README.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-OnePlus-Nord-3-${{ steps.suffix_step.outputs.suffix }}
          path: Kernel-OnePlus-Nord-3-*.zip
